### POST creates a new patient entity
POST http://localhost:8080/patients
Content-Type: application/json

{
    "name": "Sam Altman",
    "email": "",
    "address": "123 main st",
    "dateOfBirth": "1995-09-09",
    "registeredDate": "2024-11-28"
}